# Generated by Django 4.1 on 2022-08-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_complaint_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
