# Generated by Django 4.1 on 2022-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_complaint_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_info",
            name="name",
            field=models.CharField(default="john doe", max_length=100),
        ),
    ]
